### ISSUE TITLE
Add guide for how students can contribute to the website 

### ISSUE THREAD

**Issue by ArsalaBangash** [UTM-Hacklab/utmhacklab.tech#11]

**Comment by milindvishnoi** [comment]
Is this issue still open? Can I work on this?

**Comment by ArsalaBangash** [comment]
Thank you for commenting! I had completed this task and deployed it over at https://utmhacklab.tech/contributing/ 

One useful addition to the contributing ideas portion would be creating Github Issue Templates 

https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository

https://github.com/stevemao/github-issue-templates/
