### ISSUE TITLE
I'd love to help people out with side projects

### ISSUE THREAD

**Issue by lunaroyster** [UTM-Hacklab/utmhacklab.tech#14]
I've built some things:

[latex.guide](https://latex.guide)

[Indices](https://www.producthunt.com/posts/indices)

[hyperConsole](https://hyperconsole.netlify.com/)

[deeplink.space](https://deeplink.space/arnav)

[Crowd-sourced info gathering during a flood](https://www.freecodecamp.org/news/how-i-used-crowdsourcing-to-help-kerala-floods-rescue-operations-12dc97c9a24b/)

I think I understand the flow of launching side projects to Product Hunt and HN

It would be fun to meet other folks building cool things or bootstrapping startups!

**Comment by ArsalaBangash** [comment]
@lunaroyster  This was never addressed.
