### ISSUE TITLE
Curate resources

### ISSUE THREAD

**Issue by lunaroyster** [UTM-Hacklab/utmhacklab.tech#21]
Reply to this issue with high-value resources for students at UofT. Remember to tag them. 

Add things that you've found helpful in learning, building things, or anything else a hacklab student would love.

[meta]

**Comment by lunaroyster** [comment]
**Product Hunt**:

* The best place on the internet to launch your new project and get high quality feedback.
* A lot of the products launched are themselves curation lists.
* The community is beautiful and worth understanding.

[building products] [curation] [online community]

**Comment by lunaroyster** [comment]
**Paul Graham's blog & YCombinator blog**

* Some of the best ideas about the future and building things, and solving the most important impediments in your way

[building startups] [philosophy]

**Comment by lunaroyster** [comment]
**Peter Thiel's writing (Zero to One and other essays + podcasts)**

* A novel view of the world; a philosophy of getting back to the future.
* A unique view of human psychology (René Girard)

[building startups] [philosophy] [thiel] [future]

**Comment by lunaroyster** [comment]
**David Perell's writing**

* Perhaps one of the best resources on writing in the digital world.
* It's useful to understand the distinction between writing styles. Check out the section on [The Writing Scene](https://www.perell.com/blog/thoughts-on-san-francisco)

[writing]

**Comment by lunaroyster** [comment]
**[sindresorhus/awesome](https://github.com/sindresorhus/awesome)**

* A curated list of resources.

Note: The use of GitHub as curation platform is also worth checking out.

[curation] [list]

**Comment by lunaroyster** [comment]
**IndieHackers**

* You can look up the stories of other indie hackers who fit similar tech skill or business model profiles as you do. 

[building startups] [building products] [curation] [online community]

**Comment by lunaroyster** [comment]
**Wes Bos**

* Wes Bos is an engineer who's made excellent courses for many web technologies.

* https://wesbos.com/about/

[person] [building products] [courses]

**Comment by ShabazBadshah** [comment]
**Traversy**

- Brad Traversy is a freelance teacher who's made amazing course on a plethora of web design tech. He also covers the state of the web every year and talks about where it's heading, and how to prep for it
- https://www.youtube.com/user/TechGuyWeb

[person] [building products] [courses]

**Comment by DigestedLime** [comment]
**UofT Study Spot**
- UofT Study Spot is a website that finds unused classrooms and other study areas for use for UTM and UTSG students.
- http://uoftstudyspot.com/lookup-tool

[website] [studying]

**Comment by DigestedLime** [comment]
**Adobe Color**

- Like coolors.co, Adobe Color allows designers to find aesthetic colour palettes for whatever project they need. It allows for other types of option, such as monochrome palettes.
- https://color.adobe.com/create

[website] [design]

**Comment by DigestedLime** [comment]
**Griddy**

- Griddy is a tool to allow UofT students to test out different timetable layouts with course offerings at all three campuses.
- http://griddy.org/

[website] [courses] [planning]

**Comment by ArsalaBangash** [comment]
We have a curated collections page up now at https://utmhacklab.tech/resources/collections
