### ISSUE TITLE
Clean up & organize Resources page

### ISSUE THREAD

**Issue by alinakhan17** [UTM-Hacklab/utmhacklab.tech#25]

**Comment by ArsalaBangash** [comment]
What do we want the high level categories here to be?

A couple come to mind:
- UTM Courses
- Health and Well Being
- Collaboration Tools
- Web Development
- Android Development
- Design
- AI and Machine Learning
- Blockchain and Cryptocurrency
- Robotics
- Curiosity and Wonder

I'm sure there are many more that'll come to mind. I think these would be good in a grid like [Startup Stash](https://startupstash.com)

<img width="1176" alt="image" src="https://user-images.githubusercontent.com/19757203/75313607-4a344900-582b-11ea-8adb-6ffb26d669b0.png">
