### ISSUE TITLE
Fix resource box grid

### ISSUE THREAD

**Issue by AaronCGoidel** [UTM-Hacklab/utmhacklab.tech#83]
At present, the method for laying out the grid of items on the "resources" page is... wonky on mobile. 

<img width="217" alt="Current Layout Img" src="https://user-images.githubusercontent.com/11858650/88570184-a6351080-d009-11ea-995f-da3b7325fbdf.jpeg">

This can be fixed while eliminating a good portion of the code footprint that is currently being used to layout the grid, by leveraging flex-box properly.

**Comment by ArsalaBangash** [comment]
Thank you for fixing this!
